// <auto-generated />
using M4MovieDB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace M4MovieDB.Migrations
{
    [DbContext(typeof(MovieInputContext))]
    [Migration("20220127190128_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("M4MovieDB.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Category = "Comedy",
                            Director = "Jay Roach",
                            Edited = false,
                            LentTo = "Rosa",
                            Notes = "Funnies movie I own",
                            Rating = "PG",
                            Title = "Meet the Parent",
                            Year = 2000
                        },
                        new
                        {
                            MovieId = 2,
                            Category = "Action",
                            Director = "Anthony Russo",
                            Edited = false,
                            LentTo = "Jimmy",
                            Notes = "None",
                            Rating = "PG-13",
                            Title = "Avergers",
                            Year = 2012
                        },
                        new
                        {
                            MovieId = 3,
                            Category = "Documentary",
                            Director = " Jimmy Chin",
                            Edited = false,
                            LentTo = "NoOne",
                            Notes = "Free Climbing",
                            Rating = "PG-13",
                            Title = "Free Solo",
                            Year = 2018
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
